### ISSUE TITLE
remove gauges tracking code

### ISSUE THREAD

**Issue by mrtazz** [muyun/muyun.github.io#1]
heyo! I saw that you are using my blog as a template for yours. That's great! However could you make sure to remove my [gauges tracking code](https://github.com/muyun/muyun.github.io/blob/master/_includes/gauges.html) so your page views don't show up in my tracker? 

Thanks! And happy blogging! :)

**Comment by muyun** [comment]
have done;
Sorry for the inconvenience.

**Comment by muyun** [comment]
thanks a lot for your template, I like it.

**Comment by mrtazz** [comment]
awesome, thanks! Glad you like it :)
